services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Forum Domain Services
    App\BoundedContext\Forum\Domain\:
        resource: '../../src/BoundedContext/Forum/Domain/*'
        exclude: '../../src/BoundedContext/Forum/Domain/{Entity,ValueObject,Event,Exception}'

    # Application Layer
    App\BoundedContext\Forum\Application\:
        resource: '../../src/BoundedContext/Forum/Application/*'
        autowire: true
        autoconfigure: true

    # Doctrine Entity Listeners
    App\BoundedContext\Forum\Infrastructure\Doctrine\EventListener\:
        resource: '../../src/BoundedContext/Forum/Infrastructure/Doctrine/EventListener/*'
        tags: [ 'doctrine.orm.entity_listener' ]

    # Infrastructure Layer
    App\BoundedContext\Forum\Infrastructure\:
        resource: '../../src/BoundedContext/Forum/Infrastructure/*'
        exclude:
            - '../../src/BoundedContext/Forum/Infrastructure/Doctrine/Repository/*'
            - '../../src/BoundedContext/Forum/Infrastructure/Doctrine/EventListener/*'

    # Doctrine Repositories
    App\BoundedContext\Forum\Infrastructure\Doctrine\Repository\:
        resource: '../../src/BoundedContext/Forum/Infrastructure/Doctrine/Repository/*'
        autowire: true
        autoconfigure: true
        tags: ['doctrine.repository_service']
    

    # Presentation Layer - API Controllers
    App\BoundedContext\Forum\Presentation\Api\Controller\:
        resource: '../../src/BoundedContext/Forum/Presentation/Api/Controller/*'
        autowire: true
        autoconfigure: true
        tags: ['controller.service_arguments']


    # Presentation Layer - Admin
    App\BoundedContext\Forum\Presentation\Admin\:
        resource: '../../src/BoundedContext/Forum/Presentation/Admin/*'
        autowire: true
        autoconfigure: true



