a2lix_translation_form:
    locale_provider: default
    locales: ['en', 'fr']
    default_locale: '%kernel.default_locale%'
    required_locales: ['en', 'fr']
    templating: "@A2lixTranslationForm/bootstrap_3_layout.html.twig"