doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL)%'
                charset: UTF8MB4
                use_savepoints: true
                mapping_types:
                    enum: string
            dwh:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_DWH)%'
                charset: UTF8
                use_savepoints: true
                mapping_types:
                  enum: string
            audit:
                driver: pdo_mysql
                url: '%env(resolve:DATABASE_URL_AUDIT)%'
                charset: UTF8
                use_savepoints: true
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                report_fields_where_declared: true
                validate_xml_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                identity_generation_preferences:
                    Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
                auto_mapping: true
                mappings:
                    UserDomain:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/User/Domain'
                        prefix: 'App\BoundedContext\User\Domain'
                        alias: UserDomain
                    ArticleDomain:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/Article/Domain'
                        prefix: 'App\BoundedContext\Article\Domain'
                        alias: ArticleDomain
                    MessageDomain:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/Message/Domain'
                        prefix: 'App\BoundedContext\Message\Domain'
                        alias: MessageDomain
                    ForumDomain:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/Forum/Domain'
                        prefix: 'App\BoundedContext\Forum\Domain'
                        alias: ForumDomain
                    VideoGamesRecordsIgdb:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Igdb/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Igdb\Domain'
                        alias: VideoGamesRecordsIgdb
                    VideoGamesRecordsCore:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Core/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Core\Domain'
                        alias: VideoGamesRecordsCore
                    VideoGamesRecordsTeam:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Team/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Team\Domain'
                        alias: VideoGamesRecordsTeam
                    VideoGamesRecordsBadge:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Badge/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Badge\Domain'
                        alias: VideoGamesRecordsBadge
                    VideoGamesRecordsProof:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Proof/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Proof\Domain'
                        alias: VideoGamesRecordsProof
                    VideoGamesRecordsShared:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Shared/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Shared\Domain'
                        alias: VideoGamesRecordsShared
                    SharedKernel:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/SharedKernel'
                        prefix: 'App\SharedKernel'
                        alias: SharedKernel
                dql:
                    string_functions:
                        ifnull: DoctrineExtensions\Query\Mysql\IfNull
                    numeric_functions:
                        round: DoctrineExtensions\Query\Mysql\Round
                    datetime_functions:
                        date_diff: DoctrineExtensions\Query\Mysql\DateDiff
            dwh:
                connection: dwh
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    VideoGamesRecordsDwh:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/BoundedContext/VideoGamesRecords/Dwh/Domain'
                        prefix: 'App\BoundedContext\VideoGamesRecords\Dwh\Domain'
                        alias: VideoGamesRecordsDwh
            audit:
                connection: audit
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        resolve_target_entities: ~

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
