framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/src/BoundedContext/User/Resources/translations'
            - '%kernel.project_dir%/src/BoundedContext/Article/Presentation/Resources/translations'
        fallbacks:
            - en
        providers:
