# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

imports:
    - { resource: services/shared.yaml }
    - { resource: services/user.yaml }
    - { resource: admin.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/BoundedContext/*/Domain/Entity/'
            - '../src/BoundedContext/*/Domain/ValueObject/'
            - '../src/SharedKernel/Domain/Entity/'
            - '../src/SharedKernel/Domain/ValueObject/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous one
    # Rate limiter factory services
    App\Shared\EventSubscriber\RateLimitSubscriber:
        arguments:
            $apiLimiter: '@limiter.api'
            $adminLimiter: '@limiter.admin'
            $globalLimiter: '@limiter.global'
            $apiBurstLimiter: '@limiter.api_burst'
            $apiAnonymousLimiter: '@limiter.api_anonymous'
            $security: '@security.helper'

    App\Shared\EventSubscriber\LoginRateLimiterSubscriber:
        arguments:
            $loginLimiter: '@limiter.login'


